<?phpnamespace app\common\model;use think\Exception;use think\Session;//任务class Task extends BaseModel{    //发布梁型预制指令    function addTask($data)    {        $this->allowField(true)->save($data);        return true;    }    function getInstructList($data)    {        $ok = $this->where('id',$data['task_id'])            ->field([                'id',                'title',                'span',                'line',                'sound_barrier',                'sequence_number',                'catenary',                'anchor',                'cable',                'centralized_drainage',                'mould',                'technologist_affirm',            ])            ->find();        return $ok;    }    //技术员确认指定    function affirmTask($data)    {        $this->where('id',$data['task_id'])            ->update([                'technologist_affirm' => 1,                'technologist_id' => $data['user_id'],            ]);        return true;    }    //获取技术员的新任务(指令列表)    function getList($page = 1)    {        $where['t.technologist_affirm'] = 0;        //未确认的任务        $list= $this->alias('t')                ->join('user u','u.id = t.user_id','left')                ->field([                    't.id as task_id',                    't.user_id',                    'u.name',                    't.title',                    't.span',                    't.line',                    't.sound_barrier',                    't.create_time',                ])                ->where($where)                ->order('t.create_time desc')                ->paginate(6, false, ['page' => $page]);        return $list;    }}